<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LT066721" name="com.nbcd.test.TCSchedulePageMobVerifyLocalScheduleRTP4619" tests="2" failures="0" timestamp="06 Jan 2020 11:28:16 GMT" time="24.509" errors="1">
  <testcase name="MobVerifyLocalScheduleRTP4619" time="24.509" classname="com.nbcd.test.TCSchedulePageMobVerifyLocalScheduleRTP4619"/>
  <testcase name="afterSuite" time="0.000" classname="com.nbcd.test.TCSchedulePageMobVerifyLocalScheduleRTP4619">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.nbcd.GenericLib.Extent_Reports.afterSuite(Extent_Reports.java:182)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- afterSuite -->
</testsuite> <!-- com.nbcd.test.TCSchedulePageMobVerifyLocalScheduleRTP4619 -->
